on:
  workflow_call:

jobs:
  create-strategy:
    uses: ./.github/workflows/strategy.yml

  tests:
    needs: create-strategy
    runs-on: ubuntu-latest
    name: Test (Python ${{matrix.python-versions}}

    strategy:
      fail-fast: false
      matrix:
        python-version: "${{fromJson(needs.create-strategy.outputs.python-versions)}}"
        requirements-level: [pypi]

    uses: ./.github/workflows/steps.yml
