on:
  workflow_call:

jobs:
  create-strategy:
    uses: utnapischtim/test-ci/.github/workflows/strategy.yml@main

  tests:
    needs: create-strategy
    runs-on: ubuntu-latest
    name: Test (Python ${{matrix.python-version}}
    strategy:
      fail-fast: false
      matrix:
        python-version: "${{fromJson(needs.create-strategy.outputs.python-versions)}}"
        requirements-level: [pypi]
    #uses: utnapischtim/test-ci/.github/workflows/steps.yml@main
    steps:
      - name: Generate dependencies
        run: echo ${{matrix.python-version}}
